# Generated by Django 3.1.4 on 2021-02-18 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='edited_by',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='edited_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='written_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='written_by', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
